name: 🚀 Deploy on each commit
on:
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get Latest Code
      uses: actions/checkout@v4
    - name: 📂 Sync Deployment Files
      uses: burnett01/rsync-deployments@6.0.0
      with:
        remote_host: cphost.hosttechno.com
        remote_port: 2303
        remote_user: devopshostserver
        remote_path: /home2/devopshostserver/public_html/
        remote_key: ${{ secrets.SSH_KEY }}
        remote_key_pass: ${{ secrets.SSH_KEY_PASS }}
        switches: -avrz 
